=== jacobcdewitt/webxr-input-profiles/src/schemas/profile.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "https://immersive-web/gamepad-profiles/0.1.0/profile.schema.json",
    "type": "object",
    "description": "The root object for a gamepad profile.",
    "additionalProperties": false,
    "required": [ "version", "id", "handedness", "components", "dataSources"],
    "properties": {
        "version" : {
            "description": "The schema version",
            "type" : "string",
            "pattern": "^0\\.1$"
        },
        "id" : {
            "description": "The Gamepad.id the profile applies to",
            "type" : "string"
        },
        "webVR": {
            "description": "Indicates the profile file is being used with a WebVR gamepad",
            "type": "boolean"
        },
        "handedness": { "$ref": "handedness.schema.json"},
        "components": { "$ref": "components.schema.json"},
        "dataSources": { "$ref": "dataSources.schema.json"},
        "visualResponses": { "$ref": "visualResponses.schema.json"}
    }
}

=== jacobcdewitt/webxr-input-profiles/src/profiles/google-daydream/profile.json
{
    "version" : "0.1",
    "id" : "google-daydream",
    "handedness" : {
        "none" : {
            "asset" : "some-url",
            "root" : "none-controller-node",
            "components" : [0],
            "selectionComponent" : 0
        }
    },
    "components" : [
        {
            "dataSource" : 0,
            "root" : "thumbpad-node",
            "labelTransform" : "thumbpad-label-transform",
            "visualResponses" : [0, 1, 2, 3, 4]
        }
    ],
    "dataSources" : [
        {
            "id" : "thumbpad",
            "dataSourceType": "touchpadSource",
            "xAxisIndex" : 0,
            "yAxisIndex" : 1,
            "buttonIndex" : 0
        }
    ],
    "visualResponses" : [
        {
            "rootNodeName": "TOUCHPAD_TOUCH_DOT_X",
            "source": "xAxis",
            "states": ["default", "touched", "pressed"]
        },
        {
            "rootNodeName": "TOUCHPAD_TOUCH_DOT_Y",
            "source": "yAxis",
            "states": ["default", "touched", "pressed"]
        },
        {
            "rootNodeName": "TOUCHPAD_TOUCH_DOT",
            "source": "state",
            "states": ["touched", "pressed"],
            "property": "visibility"
        },
        {
            "rootNodeName": "TOUCHPAD_PRESS_X",
            "source": "xAxis",
            "states": ["pressed"]
        },
        {
            "rootNodeName": "TOUCHPAD_PRESS_Y",
            "source": "yAxis",
            "states": ["pressed"]
        }
    ]
}
