=== jacobcdewitt/webxr-input-profiles/src/schemas/profile.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "https://immersive-web/gamepad-profiles/0.1.0/profile.schema.json",
    "type": "object",
    "description": "The root object for a gamepad profile.",
    "additionalProperties": false,
    "required": [ "version", "id", "handedness", "components", "dataSources"],
    "properties": {
        "version" : {
            "description": "The schema version",
            "type" : "string",
            "pattern": "^0\\.1$"
        },
        "id" : {
            "description": "The Gamepad.id the profile applies to",
            "type" : "string"
        },
        "webVR": {
            "description": "Indicates the profile file is being used with a WebVR gamepad",
            "type": "boolean"
        },
        "handedness": { "$ref": "handedness.schema.json"},
        "components": { "$ref": "components.schema.json"},
        "dataSources": { "$ref": "dataSources.schema.json"},
        "visualResponses": { "$ref": "visualResponses.schema.json"}
    }
}

=== jacobcdewitt/webxr-input-profiles/src/profiles/WebVR Oculus Go Controller/profile.json
{
    "version" : "0.1",
    "id" : "WebVR Oculus Go Controller",
    "webVR": true,
    "handedness" : {
        "left" : {
            "asset" : "some-url",
            "root" : "controller-node",
            "webVR_targetRayOrigin": "left-controller-pointing-origin",
            "components" : [0, 1, 2],
            "selectionComponent" : 1
        },
        "right" : {
            "asset" : "some-url",
            "root" : "controller-node",
            "webVR_targetRayOrigin": "right-controller-pointing-origin",
            "components" : [0, 1, 2],
            "selectionComponent" : 1
        }
    },
    "components" : [
        {
            "dataSource" : 0,
            "root" : "touchpad-root",
            "labelTransform" : "touchpad-label-transform",
            "touchpadDot" : "touchpad-dot",
            "visualResponses": [0, 1, 2, 3]
        },
        {
            "dataSource" : 1,
            "root" : "trigger-root",
            "labelTransform" : "trigger-label-transform",
            "visualResponses": [4]
        },
        {
            "dataSource" : 2,
            "root" : "facebutton-root",
            "labelTransform" : "facebutton-label-transform",
            "visualResponses": [5]
        }
    ],
    "dataSources" : [
        {
            "id" : "touchpad",
            "dataSourceType": "touchpadSource",
            "xAxisIndex" : 0,
            "yAxisIndex" : 1,
            "buttonIndex" : 0
        },
        {
            "id" : "trigger",
            "dataSourceType": "buttonSource",
            "buttonIndex" : 1,
            "analogValues" : true
        },
        {
            "id" : "faceButton",
            "dataSourceType": "buttonSource",
            "buttonIndex" : 2
        }
    ],
    "visualResponses" : [
        {
            "rootNodeName": "TOUCHPAD_PRESS",
            "source" : "state",
            "states" : ["pressed"]
        },
        {
            "rootNodeName": "TOUCH",
            "source" : "state",
            "states" : ["touched", "pressed"],
            "property": "visibility"
        },
        {
            "rootNodeName": "TOUCHPAD_TOUCH_X",
            "source" : "xAxis",
            "states" : ["default", "touched", "pressed"]
        },
        {
            "rootNodeName": "TOUCHPAD_TOUCH_Y",
            "source" : "yAxis",
            "states" : ["default", "touched", "pressed"]
        },
        {
            "rootNodeName" : "TRIGGER",
            "source" : "buttonValue",
            "states" : ["default", "touched", "pressed"]
        },
        {
            "rootNodeName" : "FACE_BUTTON",
            "source" : "state",
            "states" : ["pressed"]
        }
    ]
}

=== jacobcdewitt/webxr-input-profiles/dist/profiles/samsung-gearvr/profile.json
{
    "version" : "0.1",
    "id" : "samsung-gearvr",
    "handedness" : {
        "none" : {
            "asset" : "some-url",
            "root" : "none-controller-node",
            "components" : [0, 1],
            "selectionComponent" : 0
        }
    },
    "components" : [
        {
            "dataSource" : 0,
            "root" : "touchpad-node",
            "labelTransform" : "touchpad-label-transform",
            "touchpadDot" : "touchpad-dot",
            "visualResponses": [0, 1, 2, 3]
        },
        {
            "dataSource" : 1,
            "root" : "faceButton-node",
            "labelTransform" : "faceButton-label-transform",
            "visualResponses": [4]
        }
    ],
    "dataSources" : [
        {
            "id" : "touchpad",
            "dataSourceType": "touchpadSource",
            "xAxisIndex" : 0,
            "yAxisIndex" : 1,
            "buttonIndex" : 0
        },
        {
            "id" : "faceButton",
            "dataSourceType": "buttonSource",
            "buttonIndex" : 1
        }
    ],
    "visualResponses" : [
        {
            "rootNodeName": "TOUCHPAD_PRESS",
            "source" : "state",
            "states" : ["pressed"]
        },
        {
            "rootNodeName": "TOUCH",
            "source" : "state",
            "states" : ["touched", "pressed"],
            "property": "visibility"
        },
        {
            "rootNodeName": "TOUCHPAD_TOUCH_X",
            "source" : "xAxis",
            "states" : ["default", "touched", "pressed"]
        },
        {
            "rootNodeName": "TOUCHPAD_TOUCH_Y",
            "source" : "yAxis",
            "states" : ["default", "touched", "pressed"]
        },
        {
            "rootNodeName" : "FACE_BUTTON",
            "source" : "state",
            "states" : ["pressed"]
        }
    ]
}

=== jacobcdewitt/webxr-input-profiles/src/profiles/WebVR Spatial Controller (Spatial Interaction Source) 045E-065D/profile.json
{
    "version" : "0.1",
    "id" : "WebVR Spatial Controller (Spatial Interaction Source) 045E-065D",
    "webVR": true,
    "handedness" : {
        "left" : {
            "asset" : "left.glb",
            "root" : "left-controller-node",
            "webVR_targetRayOrigin": "left-controller-pointing-origin",
            "components" : [0, 1, 2, 3, 4],
            "selectionComponent" : 0
        },
        "right" : {
            "asset" : "right.glb",
            "root" : "right-controller-node",
            "webVR_targetRayOrigin": "right-controller-pointing-origin",
            "components" : [0, 1, 2, 3, 4],
            "selectionComponent" : 0
        }
    },
    "components" : [
        {
            "dataSource" : 0,
            "root" : "SELECT",
            "labelTransform" : "trigger-label",
            "visualResponses": [0]
        },
        {
            "dataSource" : 1,
            "root" : "THUMBSTICK_PRESS",
            "labelTransform" : "thumbstick-label",
            "visualResponses": [1, 2, 3]
        },
        {
            "dataSource" : 2,
            "root" : "GRASP",
            "labelTransform" : "grip-label",
            "visualResponses": [4]
        },
        {
            "dataSource" : 3,
            "root" : "TOUCHPAD_PRESS",
            "labelTransform" : "grip-label",
            "visualResponses": [5, 6, 7, 8],
            "touchpadDot" : "TOUCH"
        },
        {
            "dataSource" : 4,
            "root" : "MENU",
            "labelTransform" : "menu-label",
            "visualResponses": [9]
        }
    ],
    "dataSources" : [
        {
            "id" : "trigger",
            "dataSourceType": "buttonSource",
            "buttonIndex": 0,
            "analogValues": true
        },
        {
            "id" : "thumbstick",
            "dataSourceType": "thumbstickSource",
            "xAxisIndex" : 0,
            "yAxisIndex" : 1,
            "buttonIndex" : 1
        },
        {
            "id" : "grip",
            "dataSourceType": "buttonSource",
            "buttonIndex" : 2
        },
        {
            "id" : "touchpad",
            "dataSourceType": "touchpadSource",
            "xAxisIndex" : 2,
            "yAxisIndex" : 3,
            "buttonIndex" : 3
        },
        {
            "id" : "menu",
            "dataSourceType": "buttonSource",
            "buttonIndex" : 4
        }
    ],
    "visualResponses" : [
        {
            "rootNodeName" : "SELECT",
            "source" : "buttonValue",
            "states" : ["default", "touched", "pressed"],
            "minNodeName": "UNPRESSED",
            "maxNodeName": "PRESSED"
        },
        {
            "rootNodeName": "THUMBSTICK_PRESS",
            "source" : "state",
            "states" : ["pressed"],
            "minNodeName": "UNPRESSED",
            "maxNodeName": "PRESSED"
        },
        {
            "rootNodeName": "THUMBSTICK_X",
            "source" : "xAxis",
            "states" : ["default", "touched", "pressed"]
        },
        {
            "rootNodeName": "THUMBSTICK_Y",
            "source" : "yAxis",
            "states" : ["default", "touched", "pressed"]
        },
        {
            "rootNodeName" : "GRASP",
            "source" : "state",
            "states" : ["pressed"],
            "minNodeName": "UNPRESSED",
            "maxNodeName": "PRESSED"
        },
        {
            "rootNodeName": "TOUCHPAD_PRESS",
            "source" : "state",
            "states" : ["pressed"],
            "minNodeName": "UNPRESSED",
            "maxNodeName": "PRESSED"
        },
        {
            "rootNodeName": "TOUCH",
            "source" : "state",
            "states" : ["touched", "pressed"],
            "property": "visibility"
        },
        {
            "rootNodeName": "TOUCHPAD_TOUCH_X",
            "source" : "xAxis",
            "states" : ["default", "touched", "pressed"]
        },
        {
            "rootNodeName": "TOUCHPAD_TOUCH_Y",
            "source" : "yAxis",
            "states" : ["default", "touched", "pressed"]
        },
        {
            "rootNodeName" : "MENU",
            "source" : "state",
            "states" : ["pressed"],
            "minNodeName": "UNPRESSED",
            "maxNodeName": "PRESSED"
        }
    ]
}

=== jacobcdewitt/webxr-input-profiles/src/profiles/touchpad-controller/profile.json
{
    "version" : "0.1",
    "id" : "touchpad-controller",
    "handedness" : {
        "none" : {
            "asset" : "some-url",
            "root" : "none-controller-node",
            "components" : [0],
            "selectionComponent" : 0
        },
        "left" : {
            "asset" : "some-url",
            "root" : "none-controller-node",
            "components" : [0],
            "selectionComponent" : 0
        },
        "right" : {
            "asset" : "some-url",
            "root" : "none-controller-node",
            "components" : [0],
            "selectionComponent" : 0
        }
    },
    "components" : [
        {
            "dataSource" : 0,
            "root" : "touchpad-node",
            "labelTransform" : "touchpad-label-transform",
            "touchpadDot" : "touchpad-dot",
            "visualResponses" : [0, 1, 2, 3]
        }
    ],
    "dataSources" : [
        {
            "id" : "touchpad",
            "dataSourceType": "touchpadSource",
            "xAxisIndex" : 0,
            "yAxisIndex" : 1,
            "buttonIndex" : 2
        }
    ],
    "visualResponses" : [
        {
            "rootNodeName": "TOUCHPAD_PRESS",
            "source" : "state",
            "states" : ["pressed"]
        },
        {
            "rootNodeName": "TOUCH",
            "source" : "state",
            "states" : ["touched", "pressed"],
            "property": "visibility"
        },
        {
            "rootNodeName": "TOUCHPAD_TOUCH_X",
            "source" : "xAxis",
            "states" : ["default", "touched", "pressed"]
        },
        {
            "rootNodeName": "TOUCHPAD_TOUCH_Y",
            "source" : "yAxis",
            "states" : ["default", "touched", "pressed"]
        }
    ]
}

=== jacobcdewitt/webxr-input-profiles/dist/profiles/button-controller/profile.json
{
    "version" : "0.1",
    "id" : "button-controller",
    "handedness" : {
        "none" : {
            "asset" : "some-url",
            "root" : "none-controller-node",
            "components" : [0],
            "selectionComponent": 0
        },
        "left" : {
            "asset" : "some-url",
            "root" : "none-controller-node",
            "components" : [0],
            "selectionComponent": 0
        },
        "right" : {
            "asset" : "some-url",
            "root" : "none-controller-node",
            "components" : [0],
            "selectionComponent": 0
        }
    },
    "components" : [
        {
            "dataSource" : 0,
            "root" : "button-node",
            "labelTransform" : "button-label-transform",
            "visualResponses" : [0]
        }
    ],
    "dataSources" : [
        {
            "id" : "button",
            "dataSourceType": "buttonSource",
            "buttonIndex" : 0
        }
    ],
    "visualResponses" : [
        {
            "rootNodeName" : "SELECT",
            "source" : "buttonValue",
            "states" : ["default", "touched", "pressed"]
        }
    ]
}

=== jacobcdewitt/webxr-input-profiles/dist/profiles/WebVR OpenVR Gamepad/profile.json
{
    "version" : "0.1",
    "id" : "WebVR OpenVR Gamepad",
    "webVR": true,
    "handedness" : {
        "none" : {
            "asset" : "some-url",
            "root" : "none-controller-node",
            "webVR_targetRayOrigin": "none-controller-pointing-origin",
            "components" : [0, 1, 2],
            "selectionComponent" : 0
        },
        "left" : {
            "asset" : "some-url",
            "root" : "none-controller-node",
            "webVR_targetRayOrigin": "none-controller-pointing-origin",
            "components" : [0, 1, 2],
            "selectionComponent" : 0
        },
        "right" : {
            "asset" : "some-url",
            "root" : "none-controller-node",
            "webVR_targetRayOrigin": "none-controller-pointing-origin",
            "components" : [0, 1, 2],
            "selectionComponent" : 0
        }
    },
    "components" : [
        {
            "dataSource" : 0,
            "root" : "trackpad-node",
            "labelTransform" : "trackpad-label-transform",
            "visualResponses": [0, 1, 2, 3, 4, 5],
            "touchpadDot" : "touchpad-dot"
        },
        {
            "dataSource" : 1,
            "root" : "trigger-node",
            "labelTransform" : "trigger-label-transform",
            "visualResponses": [6]
        },
        {
            "dataSource" : 2,
            "root" : "faceButton-node",
            "labelTransform" : "faceButton-label-transform",
            "visualResponses": [7]
        }
    ],
    "dataSources" : [
        {
            "id" : "trackpad",
            "dataSourceType": "touchpadSource",
            "xAxisIndex" : 0,
            "yAxisIndex" : 1,
            "buttonIndex" : 0
        },
        {
            "id" : "trigger",
            "dataSourceType": "buttonSource",
            "buttonIndex" : 1,
            "analogValues" : true
        },
        {
            "id" : "grip",
            "dataSourceType": "buttonSource",
            "buttonIndex" : 2
        }
    ],
    "visualResponses" : [
        {
            "rootNodeName": "TOUCHPAD_PRESS",
            "source" : "state",
            "states" : ["pressed"]
        },
        {
            "rootNodeName": "TOUCHPAD_PRESS_X",
            "source" : "xAxis",
            "states" : ["pressed"]
        },
        {
            "rootNodeName": "TOUCHPAD_PRESS_Y",
            "source" : "yAxis",
            "states" : ["pressed"]
        },
        {
            "rootNodeName": "TOUCHPAD_TOUCH",
            "source" : "state",
            "states" : ["touched", "pressed"]
        },
        {
            "rootNodeName": "TOUCHPAD_TOUCH_X",
            "source" : "xAxis",
            "states" : ["touched", "pressed"]
        },
        {
            "rootNodeName": "TOUCHPAD_TOUCH_Y",
            "source" : "yAxis",
            "states" : ["touched", "pressed"]
        },
        {
            "rootNodeName" : "TRIGGER",
            "source" : "buttonValue",
            "states" : ["default", "touched", "pressed"]
        },
        {
            "rootNodeName" : "FACE_BUTTON",
            "source" : "buttonValue",
            "states" : ["default", "touched", "pressed"]
        }
    ]
}

=== jacobcdewitt/webxr-input-profiles/dist/profiles/WebVR Oculus Touch (Left)/profile.json
{
    "version" : "0.1",
    "id" : "WebVR Oculus Touch (Left)",
    "webVR": true,
    "handedness" : {
        "left" : {
            "asset" : "some-url",
            "root" : "left-controller-node",
            "webVR_targetRayOrigin": "left-controller-pointing-origin",
            "components" : [0, 1, 2, 3, 4, 7],
            "selectionComponent" : 1
        },
        "right" : {
            "asset" : "some-url",
            "root" : "right-controller-node",
            "webVR_targetRayOrigin": "right-controller-pointing-origin",
            "components" : [0, 1, 2, 5, 6, 7],
            "selectionComponent" : 1
        }
    },
    "components" : [
        {
            "dataSource" : 0,
            "root" : "thumbstick-node",
            "labelTransform" : "thumbstick-label",
            "visualResponses": [0, 1, 2]
        },
        {
            "dataSource" : 1,
            "root" : "trigger-node",
            "labelTransform" : "trigger-label",
            "visualResponses": [3]
        },
        {
            "dataSource" : 2,
            "root" : "grip-node",
            "labelTransform" : "grip-label",
            "visualResponses": [4]
        },
        {
            "dataSource" : 3,
            "root" : "x-node",
            "labelTransform" : "x-label",
            "visualResponses": [7]
        },
        {
            "dataSource" : 4,
            "root" : "y-node",
            "labelTransform" : "y-label",
            "visualResponses": [8]
        },
        {
            "dataSource" : 5,
            "root" : "a-node",
            "labelTransform" : "a-label",
            "visualResponses": [5]
        },
        {
            "dataSource" : 6,
            "root" : "b-node",
            "labelTransform" : "b-label",
            "visualResponses": [6]
        },
        {
            "dataSource" : 7,
            "root" : "thumbrest-node",
            "labelTransform" : "thumbrest-label",
            "visualResponses": [9]
        }
    ],
    "dataSources" : [
        {
            "id" : "thumbstick",
            "dataSourceType": "thumbstickSource",
            "xAxisIndex" : 0,
            "yAxisIndex" : 1,
            "buttonIndex" : 0
        },
        {
            "id" : "trigger",
            "dataSourceType": "buttonSource",
            "buttonIndex" : 1,
            "analogValues" : true
        },
        {
            "id" : "grip",
            "dataSourceType": "buttonSource",
            "buttonIndex" : 2
        },
        {
            "id" : "x",
            "dataSourceType": "buttonSource",
            "buttonIndex" : 3
        },
        {
            "id" : "y",
            "dataSourceType": "buttonSource",
            "buttonIndex" : 4
        },
        {
            "id" : "a",
            "dataSourceType": "buttonSource",
            "buttonIndex" : 3
        },
        {
            "id" : "b",
            "dataSourceType": "buttonSource",
            "buttonIndex" : 4
        },
        {
            "id" : "thumbrest",
            "dataSourceType": "buttonSource",
            "buttonIndex" : 5,
            "pressUnsupported": true
        }
    ],
    "visualResponses" : [
        {
            "rootNodeName": "THUMBSTICK_PRESS",
            "source" : "state",
            "states" : ["pressed"]
        },
        {
            "rootNodeName": "THUMBSTICK_X",
            "source" : "xAxis",
            "states" : ["default", "touched", "pressed"]
        },
        {
            "rootNodeName": "THUMBSTICK_Y",
            "source" : "yAxis",
            "states" : ["default", "touched", "pressed"]
        },
        {
            "rootNodeName" : "TRIGGER",
            "source" : "buttonValue",
            "states" : ["default", "touched", "pressed"]
        },
        {
            "rootNodeName" : "GRIP",
            "source" : "state",
            "states" : ["pressed"]
        },
        {
            "rootNodeName" : "A",
            "source" : "state",
            "states" : ["pressed"]
        },
        {
            "rootNodeName" : "B",
            "source" : "state",
            "states" : ["pressed"]
        },
        {
            "rootNodeName" : "X",
            "source" : "state",
            "states" : ["pressed"]
        },
        {
            "rootNodeName" : "Y",
            "source" : "state",
            "states" : ["pressed"]
        },
        {
            "rootNodeName" : "THUMBREST",
            "source" : "state",
            "states" : ["touched", "pressed"],
            "property" : "visibility"
        }
    ]
}

=== jacobcdewitt/webxr-input-profiles/src/profiles/thumbstick-controller/profile.json
{
    "version" : "0.1",
    "id" : "thumbstick-controller",
    "handedness" : {
        "none" : {
            "asset" : "some-url",
            "root" : "none-controller-node",
            "components" : [0],
            "selectionComponent" : 0
        },
        "left" : {
            "asset" : "some-url",
            "root" : "none-controller-node",
            "components" : [0],
            "selectionComponent" : 0
        },
        "right" : {
            "asset" : "some-url",
            "root" : "none-controller-node",
            "components" : [0],
            "selectionComponent" : 0
        }
    },
    "components" : [
        {
            "dataSource" : 0,
            "root" : "thumbstick-node",
            "labelTransform" : "thumbstick-label-transform",
            "visualResponses" : [0, 1, 2]
        }
    ],
    "dataSources" : [
        {
            "id" : "thumbstick",
            "dataSourceType": "thumbstickSource",
            "xAxisIndex" : 2,
            "yAxisIndex" : 3,
            "buttonIndex" : 3
        }
    ],
    "visualResponses" : [
        {
            "rootNodeName": "THUMBSTICK_PRESS",
            "source" : "state",
            "states" : ["pressed"]
        },
        {
            "rootNodeName": "THUMBSTICK_X",
            "source" : "xAxis",
            "states" : ["default", "touched", "pressed"]
        },
        {
            "rootNodeName": "THUMBSTICK_Y",
            "source" : "yAxis",
            "states" : ["default", "touched", "pressed"]
        }
    ]
}
